### ISSUE TITLE
P2P code review

### ISSUE THREAD

**Issue by dili021** [dili021/my-portfolio#1]

**Comment by patriciachrysy** [comment]
Good job on the details and the effects, especially the colors effects!!! Keep the good work!!!

**Comment by rammazzoti2000** [comment]
I like the mobile version with the bottom social bar, cool! Also the hover effect is a great move. Overall I really like it, especially the color combinations it is light on the eyes.

**Comment by nyatindopatrick** [comment]
Good job! Great design.

**Comment by dili021** [comment]
Thanks guys! Much appreciated.
