### ISSUE TITLE
p2p re-re-re-review :)

### ISSUE THREAD

**Issue by dili021** [dili021/my-portfolio#2]

**Comment by rammazzoti2000** [comment]
The project has a great concept design and I like the small details added.
On scroll you could remove the transparency  on the navbar and leave it only when on top of page.

**Comment by nyatindopatrick** [comment]
Nice work. Apart from what Alex has pointed out in the navbar, it's all great!

**Comment by patriciachrysy** [comment]
Good job overall, but i wish you could come back to the previous design, it was pretty awesome!!

**Comment by dili021** [comment]
Thanks for the comments guys, I'll take them all into consideration.
